//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TLAClientDemo.rc
//
#define ID_RESET                        3
#define IDC_RESET                       3
#define IDC_CORRECTIONS                 3
#define IDC_CONNECT                     3
#define IDC_GAIN_CORRECTIONS            3
#define IDC_CORRECTIONS_FOCUS           4
#define IDC_RUN_AID                     4
#define IDC_FILM_TRACK                  5
#define IDC_RESET_LEDS                  5
#define IDC_IMPORT                      6
#define IDC_CORRECTIONS_FOCUS_ADVANCE_FILM 7
#define IDC_RESET_MOTOR_SPEED_ADJUST    8
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TLACLIENTDEMO_DIALOG        102
#define IDS_COM_ERROR_TITLE             110
#define IDS_COM_ERROR01                 111
#define IDS_COM_ERROR02                 112
#define IDS_COM_ERROR03                 113
#define IDS_COM_ERROR04                 114
#define IDS_COM_ERROR05                 115
#define IDS_COM_ERROR06                 116
#define IDS_COM_ERROR07                 117
#define IDS_COM_ERROR08                 118
#define IDS_COM_ERROR09                 119
#define IDS_COM_ERROR10                 120
#define IDS_COM_ERROR11                 121
#define IDS_COM_ERROR12                 122
#define IDS_COM_ERROR13                 123
#define IDS_COM_ERROR14                 124
#define IDS_COM_ERROR15                 125
#define IDS_COM_ERROR16                 126
#define IDS_COM_ERROR17                 127
#define IDR_MAINFRAME                   128
#define IDS_COM_ERROR18                 128
#define IDS_COM_ERROR19                 129
#define IDD_SCAN_DIALOG                 130
#define IDS_COM_ERROR20                 130
#define IDD_SAVE_DIALOG                 131
#define IDS_COM_ERROR21                 131
#define IDS_COM_ERROR22                 132
#define IDD_FRAME_DIALOG                133
#define IDS_COM_ERROR23                 133
#define IDD_COLOR_DIALOG                134
#define IDS_COM_ERROR24                 134
#define IDD_PRE_FRAME_35_DIALOG         135
#define IDD_PRE_SCAN_DIALOG             135
#define IDS_COM_ERROR25                 135
#define IDD_DELETE_ROLL                 136
#define IDS_COM_ERROR26                 136
#define IDD_ADVANCE_MOTOR               137
#define IDS_COM_ERROR27                 137
#define IDS_COM_ERROR28                 138
#define IDS_COM_ERROR29                 139
#define IDS_COM_ERROR30                 140
#define IDS_COM_ERROR_SCAN              200
#define IDS_COM_ERROR_SAVE              201
#define IDS_COM_ERROR_SHUTDOWN          202
#define IDS_COM_ERROR_ADVANCE_FILM      203
#define IDS_COM_ERROR_NO_DATA           204
#define IDS_COM_ERROR_CORRECTIONS       205
#define IDS_COM_ERROR_TRACK_TEST        206
#define IDS_COM_ERROR_IMPORT            207
#define IDS_COM_ERROR_PRESSURE_ROLLERS  208
#define IDS_COM_ERROR_HARDWARE_APS      209
#define IDS_COM_ERROR_INITIALIZE        210
#define IDS_COM_ERROR_HARDWARE          211
#define IDS_COM_ERROR_LAMP_WARMUP       212
#define IDS_COM_ERROR_F235C_MANUALRETRACT 213
#define IDS_COM_ERROR_FIRMWARE_APS      214
#define IDS_COM_ERROR_FIRMWARE_CCD      215
#define IDS_COM_ERROR_FIRMWARE_DX       216
#define IDS_COM_ERROR_FIRMWARE_LAMP     217
#define IDS_COM_ERROR_FIRMWARE_MOTOR    218
#define IDS_COM_ERROR_EXERCISE_STEPPERS 219
#define IDC_SCAN                        1000
#define IDC_SCAN_CANCEL                 1001
#define IDC_SAV_METHOD_MEMORY_CLIENT    1001
#define IDC_SAVE                        1002
#define IDC_PLANAR                      1002
#define IDC_PRE_SCAN                    1003
#define IDC_8BIT_DIB                    1003
#define IDC_SAVE_CANCEL                 1004
#define IDC_16BIT_DIB                   1004
#define IDC_ADVANCE_FILM                1005
#define IDC_SAV_METHOD_DISK             1005
#define IDC_NEXT                        1006
#define IDC_PREVIOUS                    1007
#define IDC_APPLY                       1008
#define IDC_PROGRESS                    1009
#define IDC_SCAN_PROGRESS               1009
#define IDC_SAVE_PROGRESS               1010
#define IDC_PICTURE                     1011
#define IDC_FILM_FORMAT_35MM            1012
#define IDC_RELEASE_SAVE_GROUP          1012
#define IDC_FILM_FORMAT_24MM            1013
#define IDC_MOVE_TO_SAVE_GROUP          1013
#define IDC_FILM_COLOR_NEGATIVE         1014
#define IDC_SAV_USE_COLOR_ADJUSTMENTS   1014
#define IDC_FILM_COLOR_POSITIVE         1015
#define IDC_SAV_USE_SCRATCH_REMOVAL     1015
#define IDC_FILM_COLOR_BnW              1016
#define IDC_SAV_USE_COLOR_SCENE_BALANCE 1016
#define IDC_FILM_COLOR_BnW_C41          1017
#define IDC_MIRROR                      1017
#define IDC_RESOLUTION_LO               1018
#define IDC_ROTATE                      1018
#define IDC_RESOLUTION_HI               1019
#define IDC_RESOLUTION_PLUS             1020
#define IDC_ROTATE_AMOUNT               1020
#define IDC_FILM_FORMAT_24MM_CART       1021
#define IDC_CLEAR_EXISTING              1022
#define IDC_STATIC_PROGRESS             1022
#define IDC_SCAN_STATUS                 1022
#define IDC_VERSION                     1022
#define IDC_FILM_FORMAT_24MM_CART_MOF_READER 1022
#define IDC_FRAMES_PER_STRIP_0          1023
#define IDC_SAVE_STATUS                 1023
#define IDC_MILLISECONDS                1023
#define IDC_FRAMES_PER_STRIP_4          1024
#define IDC_SPIN_SPEED                  1024
#define IDC_FRAMES_PER_STRIP_5          1025
#define IDC_SPEED                       1025
#define IDC_FRAMES_PER_STRIP_6          1026
#define IDC_FILM_FORMAT_24MM_CART_MOF_FILE 1027
#define IDC_LONG_ROLL_MODE              1028
#define IDC_SAV_USE_LO_RES_BUFFER       1028
#define IDC_EDIT1                       1028
#define IDC_FILM_FORMAT_24MM_CART_MOF_FILE_OR_READER 1028
#define IDC_REEL_TO_REEL                1029
#define IDC_SAV_USE_COLOR_CORRECTION    1029
#define IDC_READ_DX                     1030
#define IDC_SAV_USE_FLATLINE            1030
#define IDC_SAV_USE_MEMORY              1031
#define IDC_FILE_NAME                   1031
#define IDC_SAV_METHOD_MEMORY_SHARED    1031
#define IDC_SCRATCH_REMOVAL             1031
#define IDC_SAV_FAST_UPDATES            1032
#define IDC_FRAME_NUMBER                1032
#define IDC_AGGRESSIVE_FRAMING          1032
#define IDC_FILE_FORMAT_TYPE            1033
#define IDC_DO_FILM_TRACK_TEST          1033
#define IDC_FIXED_PICTURE_DIMENSION     1034
#define IDC_PICTURE_WIDTH               1034
#define IDC_LAMP_WARM_UP                1034
#define IDC_DELETE_ROLL                 1034
#define IDC_SAV_TOP_DOWN_DIB            1035
#define IDC_SPIN_ROLL                   1035
#define IDC_EXERCISE_STEPPERS           1035
#define IDC_DPI                         1036
#define IDC_DELETE_ROLL_INDEX           1036
#define IDC_FILM_DRAG                   1036
#define IDC_COMPRESSION                 1037
#define IDC_ROTATE_NEW_AMOUNT           1038
#define IDC_TEST_COUNT                  1038
#define IDC_SAV_SIZE_ORIGINAL           1039
#define IDC_FILM_FORMAT_24MM_FILE       1039
#define IDC_SAV_SIZE_DISPLAY            1040
#define IDC_SAV_SIZE_SAVE               1041
#define IDC_LOAD_FIRMWARE_AT_STARTUP    1041
#define IDC_SPIN_COMPRESSION            1042
#define IDC_SELF_TEST_AT_STARTUP        1042
#define IDC_FP_CORRECTIONS              1042
#define IDC_SPIN_DPI                    1043
#define IDC_ROTATE_CURRENT              1044
#define IDC_PICTURE_HEIGHT              1045
#define IDC_ROTATE_NEW                  1046
#define IDC_INDEX                       1047
#define IDC_SAV_PLANAR_FILE_HEADER      1047
#define IDC_PICTURE_COUNT               1048
#define IDC_SAV_DIB_FILE_HEADER         1048
#define IDC_FRAME_NAME                  1049
#define IDC_USE_WORKER_THREAD           1049
#define IDC_STRIP_NUMBER                1050
#define IDC_FILM_PRODUCT                1051
#define IDC_DIRECTORY                   1053
#define IDC_FILM_SPECIFIER              1054
#define IDC_INDEX_CURRENT               1055
#define IDC_SCAN_ROLL_COUNT             1055
#define IDC_INDEX_SELECTED              1056
#define IDC_INDEX_ALL                   1057
#define IDC_NOT_SELECTED                1060
#define IDC_RADIO2                      1061
#define IDC_RADIO3                      1062
#define IDC_FRAMING                     1064
#define IDC_LR_LEFT                     1065
#define IDC_INSERT_PICTURE              1065
#define IDC_LR_TOP                      1066
#define IDC_LR_RIGHT                    1067
#define IDC_LR_BOTTOM                   1068
#define IDC_HR_LEFT                     1069
#define IDC_PICTURE_MODE_ONE            1069
#define IDC_HR_TOP                      1070
#define IDC_PICTURE_MODE_FOUR           1070
#define IDC_HR_RIGHT                    1071
#define IDC_HR_BOTTOM                   1072
#define IDC_SLIDER_R                    1072
#define IDC_RATIO_LR_HR                 1073
#define IDC_COLOR                       1074
#define IDC_DELETE_PICTURE              1075
#define IDC_SLIDER_G                    1076
#define IDC_FRAME_OP_ADJUST             1077
#define IDC_FRAME_OP_CROP               1078
#define IDC_SLIDER_B                    1078
#define IDC_USE_RATIO                   1079
#define IDC_EDIT_LOW_RES_HEIGHT         1080
#define IDC_SLIDER_D                    1080
#define IDC_EDIT_HIGH_RES_HEIGHT        1080
#define IDC_EDIT_FILM_LENGTH_MM         1081
#define IDC_SLIDER_C                    1082
#define IDC_EDIT_HEIGHT_35              1083
#define IDC_EDIT_HIGH_RES_HEIGHT_MM     1083
#define IDC_SLIDER_SHARPNESS            1083
#define IDC_EDIT_WIDTH_35               1084
#define IDC_EDIT_WIDTH                  1084
#define IDC_EDIT_WIDTH_UNIT_35          1085
#define IDC_EDIT_WIDTH_UNIT             1085
#define IDC_EDIT_HEIGHT_OFFSET_35       1086
#define IDC_EDIT_LEFT_35                1087
#define IDC_EDIT_LEFT                   1087
#define IDC_EDIT_RIGHT_35               1088
#define IDC_EDIT_RIGHT                  1088
#define IDC_EDIT_TOP_35                 1089
#define IDC_EDIT_TOP                    1089
#define IDC_EDIT_BOTTOM_35              1090
#define IDC_EDIT_BOTTOM                 1090
#define ID_PRESCAN_35MM4BASE            32771
#define IDM_SCANNER_INFO_000            32772
#define ID_PRESCAN_35MM8BASE            32772
#define ID_PRESCAN_35MM16BASE           32773
#define ID_PRESCAN_24MM4BASE            32774
#define ID_PRESCAN_24MM8BASE            32775
#define ID_PRESCAN_24MM16BASE           32776
#define ID_HELP_ABOUT                   32777
#define IDS_COM_ERROR_FILM_GUIDES       32778
#define ID_CONTROL_LAMPOFF              32778
#define ID_CONTROL_LAMPDIM              32779
#define ID_CONTROL_LAMPON               32780
#define ID_CONTROL_ROLLERSRELEASE       32781
#define ID_CONTROL_APSMANUALRETRACT     32782
#define ID_CONTROL_DELETE_OLDEST_MOF_ROLL 32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
